# Golang CircleCI 2.0 configuration file

version: 2

jobs:
  build:

    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Check cookiecutter template
          command: tox
